export const LAYOUT_CONSTANTS = Object.freeze({
  DOCUMENT_MARGIN: 60,
  SECTION_PADDING: 24,
  TITLE_GAP: 36,
  HEADING_GAP: 32,
  CONTENT_GAP: 32,
  OBJECT_GAP: 60,
  ROW_GAP: 40,
  COLUMN_GAP: 40,
  SECTION_GAP: 80,
  NOTES_COLUMNS: 3,
  OTHER_COLUMNS: 2,
  DEFAULT_WIDTH: 120,
  DEFAULT_HEIGHT: 80,
  SECTION_MIN_WIDTH: 200,
  SECTION_MAX_WIDTH: 800,
  CANVAS_MAX_ASPECT: 2.5,
  OUTLIER_THRESHOLD: 1500,
  COLLISION_NUDGE: 16,
  MAX_COLLISION_PASSES: 3
});

export const LAYOUT_FALLBACKS = Object.freeze({
  NO_OBJECT_MODEL: 'missing-workspace-model',
  CYCLIC_DIAGRAM: 'cyclic-diagram',
  AMBIGUOUS_DIAGRAM: 'ambiguous-diagram',
  UNSUPPORTED_SECTION: 'unsupported-section'
});
